### ISSUE TITLE
Register plugins on different connections using labels?

### ISSUE THREAD

**Issue by saurabhghewari** [cbmono/hapijs-seed-mvc#29]
Great architecture and coding standards. Using this in one of my company project.

How to register plugins to server based on connection labels. For example, I want to register hapi-swagger plugin to the server but on 'docs' label connection which is listening on 8000 port and not api label. I followed the hapi-swagger documentation but did not get success.

Registering hapi-swagger on single connection of server works fine, but i want to have seperate connection listening to documentation api.

Please, guide me for this.

**Comment by saurabhghewari** [comment]
O, it was my mistake not registering Inert and vision on same labeled connection. Issues solved.
Thank you for this great architecture.
Could this be done same using Sequelize or Bookshelf ORMS?

**Comment by cbmono** [comment]
@saurabhghewari sorry, just saw this :( Glad you were able to solve your `hapi-swagger` issue. Would you mind sharing it?

> Could this be done same using Sequelize or Bookshelf ORMS?

Certainly. Though there is some work needed:

* Most important, don't expose the ORMS, but keep it encapsulated inside of `src/models/BaseModel.RDMS.js`. Models don't need to be aware of your current ORMS
* Maybe create `BaseModel.Bookshelf.js` and extend `BaseModel.RDMS.js` with it (depending on config settings)
* Extend `src/db.js` to support different ORMS'
* Create an interface to deal with Schema migrations depending on the selected ORMS `src/database/*`
