### ISSUE TITLE
Registering hapi-auth-jwt2 plugin

### ISSUE THREAD

**Issue by zolekm** [cbmono/hapijs-seed-mvc#56]
Thank you on great seed for hapijs.
I use your seed on my new project, but i stuck on registering plugin for jwt auth, because configuration you provide in hapijs.plugins.js is no option to register auth strategy, can you suggest how could this be done in right way?

Example:
```js
server.register(require('hapi-auth-jwt2'), function (err) {

    if(err){
      console.log(err);
    }

    server.auth.strategy('jwt', 'jwt',
    { key: 'NeverShareYourSecret',          // Never Share your secret key
      validateFunc: validate,            // validate function defined above
      verifyOptions: { algorithms: [ 'HS256' ] } // pick a strong algorithm
    });

    server.auth.default('jwt');
});

```
Best, M

**Comment by cbmono** [comment]
Hi @zolekm, 

You can pass an array of Plugins to [`server.register`](http://hapijs.com/tutorials/plugins#loading-a-plugin). I guess that should do the trick.

I will test it later today and let you know.

Best,
c.

**Comment by zolekm** [comment]
Thank you @cbmono 👍

**Comment by cbmono** [comment]
@zolekm please check this PR: https://github.com/cbmono/hapijs-seed-mvc/pull/57
Maybe you can finish the implementation and share it through a Fork/PR.

**Comment by zolekm** [comment]
@cbmono thanks for example i found here https://github.com/Talento90/typescript-node/tree/master/src/libs/plugins a great example how to register plugins, i think it allow us to have a more freedom on creating some extra logic that plugin may expect. With configuration file we have to register plugin in one place and making extra logic on other place which is in my opinion not so good, let me know what you think about that approach.

**Comment by cbmono** [comment]
@zolekm sure, will check it out over the weekend.

**Comment by cbmono** [comment]
@zolekm sry, took a bit longer.

I like the approach from `ts-node` and did a similar implementation. Check it out here: https://github.com/cbmono/hapijs-seed-mvc/pull/57. I will create a new PR where I add those changes to master.

I kept the example for [hapi-auth-jwt2](https://github.com/cbmono/hapijs-seed-mvc/pull/57/files#diff-695049c25bbe0cb85bcb3d752a7ff8a1R4).

**Comment by zolekm** [comment]
@cbmono this looks great i think this will make work progress much faster, with new plugin register and jwt auth
